web_analytics_project/mainapp/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('model/', views.text_model, name='model'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='about')
]

web_analytics_project/web_analytics_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('', include('mainapp.urls'))
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_analytics_project/mainapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse 

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('mainapp:post-detail', kwargs={'pk': self.pk})

web_analytics_project/mainapp/forms.py
from django import forms

class ModelForm(forms.Form):
    title = forms.CharField(max_length=20)
    start_string = forms.CharField(max_length=20)
    length = forms.IntegerField()
    file = forms.FileField()

web_analytics_project/mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from .forms import ModelForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import EmailMessage, send_mail

from .text_generation_django import generate_text_function

def home(request):
    context = {'Posts': Post.objects.all()}
    return render(request, 'mainapp/index.html', context)

def about(request):    
    return render(request, 'mainapp/about.html', {'title': 'About Us'})

class PostListView(ListView):
    model = Post
    template_name = 'mainapp/index.html'
    context_object_name = 'Posts'
    ordering = ['-date_posted']
    paginate_by = 5

class UserPostListView(ListView):
    model = Post
    template_name = 'mainapp/user_posts.html'
    context_object_name = 'Posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')

class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

@login_required
def text_model(request):
    if request.method == 'POST':
        model_form = ModelForm(request.POST, request.FILES)
        if model_form.is_valid():
            cd = model_form.cleaned_data
            title = cd.get('title')
            start_string =  cd.get('start_string')
            length =  cd.get('length')
            text = str(request.FILES['file'].read())

            subject = title + ' Generated Text'
            generated_sentences, train_perplexity, loss = generate_text_function(text, start_string, length)
            message = 'Perplexity: ' + train_perplexity + '\n' + 'Loss: ' + loss + '\n\n'
            message += '-------------------------------------------------------------------------------------------------------------------\n\n'
            index = 1
            for sentence in generated_sentences:
                message += str(index) + '. ' + sentence + '\n\n'
                index += 1
            recipient_list = [request.user.email]
            
            email = EmailMessage(subject, message, to=recipient_list)
            email.send()

            messages.success(request, f'Please check your email for the generated text')
            return redirect('mainapp:home')
    else:
        model_form = ModelForm()

    context = {'model_form': model_form}

    return render(request, 'mainapp/text_model.html', context)

web_analytics_project/mainapp/templates/mainapp/about.html
{% extends "mainapp/base.html" %}
{% block content %}
  <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <h2 class="mr-2">About Us</h2>
            <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
          </div>
          <p class="article-content">This is a website for data science enthusiasts to share posts and train models.</p>
        </div>
    </article>
{% endblock content %}

web_analytics_project/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>

    {% if title %}
        <title>{{title}}</title>
    {% else %}
        <title>Homepage</title>
    {% endif %}

    <head>

        <style>
            ul
            {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color: #333;
            }

            li
            {
                float: right;
            }

            li a
            {
                display: block;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

            li a:hover
            {
                background-color: #111;
            }

            .floatleft 
            {
                float:left;
            }
            .floatright {
                float:right;
            }

        </style>

    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css" rel="stylesheet" integrity="sha384-HzUaiJdCTIY/RL2vDPRGdEQHHahjzwoJJzGUkYjHVzTwXFQ2QN/nVgX7tzoMW3Ov" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/main.css' %}">

    </head>

    <body>

        <ul>
            <div class="floatleft"> <li><a class="active" href="{% url 'mainapp:home' %}" float="left">Home</a></li> </div>
            <div class="floatleft"> <li><a class="active" href="{% url 'mainapp:about' %}" float="left">About Us</a></li> </div>
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'profile' %}">Profile</a></li>
                <li><a href="{% url 'mainapp:post-create' %}">New Post</a></li>
                <li><a href="{% url 'mainapp:model' %}">New Model</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
            {% endif %}
        </ul>

        </br>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %} {% endblock %}
    </body>
<html>

web_analytics_project/mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% block content %}
    <h1 style="text-align: center;";>Web Analytics Project</h1>

    {% for post in Posts %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'mainapp:user-posts' post.author.username %}">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted }}</small>
          </div>
          <h2><a class="article-title" href="{% url 'mainapp:post-detail' post.id %}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page.obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}

web_analytics_project/mainapp/templates/mainapp/post_confirm_delete.html
{% extends "mainapp/base.html" %}
{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Post</legend>
        <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
      </fieldset>
      <div class="form-group">
        <input class="btn btn-outline-danger" type="submit"></input>
        <a class="btn btn-outline-secondary" href="{% url 'mainapp:post-detail' object.id %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock content %}

web_analytics_project/mainapp/templates/mainapp/post_detail.html
{% extends "mainapp/base.html" %}

{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="{% url 'mainapp:user-posts' object.author.username %}">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted }}</small>
            {% if object.author == user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'mainapp:post-update' object.id %}">Update Post</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'mainapp:post-delete' object.id %}">Delete Post</a>
                </div>
                
            {% endif %}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
        </div>
    </article>
{% endblock content %}

web_analytics_project/mainapp/templates/mainapp/post_form.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Blog Post</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <input class="btn btn-outline-info" type="submit"></input>
      </div>
    </form>
  </div>
{% endblock content %}

web_analytics_project/mainapp/templates/mainapp/text_model.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <div class="media">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Info</legend>
        {{ model_form|crispy }}
      </fieldset>
      <div class="form-group">
        <input class="btn btn-outline-info" type="submit"></input>
      </div>
    </form>
  </div>
{% endblock content %}

web_analytics_project/mainapp/templates/mainapp/user_posts.html
{% extends "mainapp/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ views.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in Posts %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'mainapp:user-posts' post.author.username %}">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted }}</small>
          </div>
          <h2><a class="article-title" href="{% url 'mainapp:post-detail' post.id %}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page.obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}